"""
Posts AI review comments back to GitHub Pull Requests.

After an agent analysis completes, this module formats the findings
into GitHub review comment format and posts them to the PR.
"""
from typing import Any

from app.github.client import GitHubClient
from app.models.pull_request import PullRequestFinding
import structlog

logger = structlog.get_logger(__name__)

SEVERITY_EMOJI = {
    "critical": "🔴",
    "warning": "🟡",
    "optimization": "🟢",
}

CONFIDENCE_LABEL = {
    "high": "High confidence",
    "medium": "Medium confidence",
    "low": "Low confidence — please verify",
}


def format_finding_as_comment(finding: PullRequestFinding) -> str:
    """
    Format a PullRequestFinding into a GitHub review comment body (Markdown).
    """
    emoji = SEVERITY_EMOJI.get(finding.severity, "⚪")
    confidence = CONFIDENCE_LABEL.get(finding.confidence, finding.confidence)

    lines = [
        f"## {emoji} DevInsight AI — {finding.severity.title()} Finding",
        f"**Agent:** `{finding.agent_type.replace('_', ' ').title()}`  |  **Confidence:** {confidence}",
        "",
        f"**Issue:** {finding.explanation}",
    ]

    if finding.suggested_fix:
        lines += [
            "",
            "**Suggested Fix:**",
            "```",
            finding.suggested_fix,
            "```",
        ]

    if finding.estimated_impact:
        lines += ["", f"**Impact:** {finding.estimated_impact}"]

    if finding.related_doc and finding.doc_url:
        lines += ["", f"**Reference:** [{finding.related_doc}]({finding.doc_url})"]

    lines += ["", "_This review was generated by DevInsight AI. [Learn more](https://devinsight.dev)_"]
    return "\n".join(lines)


async def post_pr_review(
    client: GitHubClient,
    owner: str,
    repo: str,
    pr_number: int,
    findings: list[PullRequestFinding],
    summary: str,
) -> dict[str, Any]:
    """
    Post a complete AI review with inline comments to a GitHub PR.
    Uses the GitHub Reviews API (POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews).
    """
    if not findings:
        # Post a passing review if no issues found
        body = await client.post(
            f"/repos/{owner}/{repo}/pulls/{pr_number}/reviews",
            json={
                "body": "✅ **DevInsight AI Review — No issues detected.**\n\nAll checks passed. This pull request looks good to merge.",
                "event": "APPROVE",
                "comments": [],
            },
        )
        return body

    # Build inline comments for findings with line numbers
    inline_comments = []
    for finding in findings:
        if finding.line_number and finding.file_path:
            inline_comments.append({
                "path": finding.file_path,
                "line": finding.line_number,
                "body": format_finding_as_comment(finding),
            })

    event = "REQUEST_CHANGES" if any(f.severity == "critical" for f in findings) else "COMMENT"

    result = await client.post(
        f"/repos/{owner}/{repo}/pulls/{pr_number}/reviews",
        json={
            "body": f"## 🤖 DevInsight AI Review\n\n{summary}",
            "event": event,
            "comments": inline_comments,
        },
    )

    logger.info(
        "github_review_posted",
        repo=f"{owner}/{repo}",
        pr_number=pr_number,
        findings_count=len(findings),
        inline_comments=len(inline_comments),
    )

    return result
