/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as PullRequestsRouteImport } from './routes/pull-requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmptyRouteImport } from './routes/empty'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiWorkspaceRouteImport } from './routes/ai-workspace'
import { Route as R500RouteImport } from './routes/500'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoryRepoIdRouteImport } from './routes/repository.$repoId'
import { Route as PullRequestPrIdRouteImport } from './routes/pull-request.$prId'
import { Route as BugBugIdRouteImport } from './routes/bug.$bugId'
import { Route as AgentAgentIdRouteImport } from './routes/agent.$agentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRoute = PullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyRoute = EmptyRouteImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceRoute = AiWorkspaceRouteImport.update({
  id: '/ai-workspace',
  path: '/ai-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRepoIdRoute = RepositoryRepoIdRouteImport.update({
  id: '/repository/$repoId',
  path: '/repository/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestPrIdRoute = PullRequestPrIdRouteImport.update({
  id: '/pull-request/$prId',
  path: '/pull-request/$prId',
  getParentRoute: () => rootRouteImport,
} as any)
const BugBugIdRoute = BugBugIdRouteImport.update({
  id: '/bug/$bugId',
  path: '/bug/$bugId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/ai-workspace': typeof AiWorkspaceRoute
  '/analytics': typeof AnalyticsRoute
  '/bugs': typeof BugsRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/empty': typeof EmptyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pull-requests': typeof PullRequestsRoute
  '/repositories': typeof RepositoriesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/bug/$bugId': typeof BugBugIdRoute
  '/pull-request/$prId': typeof PullRequestPrIdRoute
  '/repository/$repoId': typeof RepositoryRepoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/ai-workspace': typeof AiWorkspaceRoute
  '/analytics': typeof AnalyticsRoute
  '/bugs': typeof BugsRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/empty': typeof EmptyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pull-requests': typeof PullRequestsRoute
  '/repositories': typeof RepositoriesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/bug/$bugId': typeof BugBugIdRoute
  '/pull-request/$prId': typeof PullRequestPrIdRoute
  '/repository/$repoId': typeof RepositoryRepoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/ai-workspace': typeof AiWorkspaceRoute
  '/analytics': typeof AnalyticsRoute
  '/bugs': typeof BugsRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/empty': typeof EmptyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pull-requests': typeof PullRequestsRoute
  '/repositories': typeof RepositoriesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/bug/$bugId': typeof BugBugIdRoute
  '/pull-request/$prId': typeof PullRequestPrIdRoute
  '/repository/$repoId': typeof RepositoryRepoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/ai-workspace'
    | '/analytics'
    | '/bugs'
    | '/dashboard'
    | '/design-system'
    | '/empty'
    | '/forgot-password'
    | '/login'
    | '/pull-requests'
    | '/repositories'
    | '/signup'
    | '/sitemap.xml'
    | '/agent/$agentId'
    | '/bug/$bugId'
    | '/pull-request/$prId'
    | '/repository/$repoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/ai-workspace'
    | '/analytics'
    | '/bugs'
    | '/dashboard'
    | '/design-system'
    | '/empty'
    | '/forgot-password'
    | '/login'
    | '/pull-requests'
    | '/repositories'
    | '/signup'
    | '/sitemap.xml'
    | '/agent/$agentId'
    | '/bug/$bugId'
    | '/pull-request/$prId'
    | '/repository/$repoId'
  id:
    | '__root__'
    | '/'
    | '/500'
    | '/ai-workspace'
    | '/analytics'
    | '/bugs'
    | '/dashboard'
    | '/design-system'
    | '/empty'
    | '/forgot-password'
    | '/login'
    | '/pull-requests'
    | '/repositories'
    | '/signup'
    | '/sitemap.xml'
    | '/agent/$agentId'
    | '/bug/$bugId'
    | '/pull-request/$prId'
    | '/repository/$repoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R500Route: typeof R500Route
  AiWorkspaceRoute: typeof AiWorkspaceRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BugsRoute: typeof BugsRoute
  DashboardRoute: typeof DashboardRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EmptyRoute: typeof EmptyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PullRequestsRoute: typeof PullRequestsRoute
  RepositoriesRoute: typeof RepositoriesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AgentAgentIdRoute: typeof AgentAgentIdRoute
  BugBugIdRoute: typeof BugBugIdRoute
  PullRequestPrIdRoute: typeof PullRequestPrIdRoute
  RepositoryRepoIdRoute: typeof RepositoryRepoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests': {
      id: '/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof PullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty': {
      id: '/empty'
      path: '/empty'
      fullPath: '/empty'
      preLoaderRoute: typeof EmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace': {
      id: '/ai-workspace'
      path: '/ai-workspace'
      fullPath: '/ai-workspace'
      preLoaderRoute: typeof AiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/$repoId': {
      id: '/repository/$repoId'
      path: '/repository/$repoId'
      fullPath: '/repository/$repoId'
      preLoaderRoute: typeof RepositoryRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-request/$prId': {
      id: '/pull-request/$prId'
      path: '/pull-request/$prId'
      fullPath: '/pull-request/$prId'
      preLoaderRoute: typeof PullRequestPrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bug/$bugId': {
      id: '/bug/$bugId'
      path: '/bug/$bugId'
      fullPath: '/bug/$bugId'
      preLoaderRoute: typeof BugBugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentId': {
      id: '/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500Route: R500Route,
  AiWorkspaceRoute: AiWorkspaceRoute,
  AnalyticsRoute: AnalyticsRoute,
  BugsRoute: BugsRoute,
  DashboardRoute: DashboardRoute,
  DesignSystemRoute: DesignSystemRoute,
  EmptyRoute: EmptyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PullRequestsRoute: PullRequestsRoute,
  RepositoriesRoute: RepositoriesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AgentAgentIdRoute: AgentAgentIdRoute,
  BugBugIdRoute: BugBugIdRoute,
  PullRequestPrIdRoute: PullRequestPrIdRoute,
  RepositoryRepoIdRoute: RepositoryRepoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
